#!/usr/bin/env python3
# Natter - generate src/core/emoji_table.inc from iamcal/emoji-data.
# SPDX-License-Identifier: MIT
"""Build the compact shortcode -> Unicode table Natter compiles in.

The input is emoji.json from https://github.com/iamcal/emoji-data (MIT
licensed; the data set Slack itself uses). It is not kept in the repository:

    curl -L -o $OVERFLOW/emoji.json \
        https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json
    tools/gen_emoji_table.py $OVERFLOW/emoji.json src/core/emoji_table.inc

Output layout:
  kEmojiSequences[]  one UTF-8 string per emoji (the fully qualified form) and
                     a flag saying whether it takes a skin tone;
  kEmojiNames[]      every short name, sorted, pointing into kEmojiSequences;
  kToneOverrides[]   the few emoji (two-person ones) whose toned forms do not
                     follow the "modifier after the first code point" rule.
"""

import hashlib
import json
import sys

TONES = ["1F3FB", "1F3FC", "1F3FD", "1F3FE", "1F3FF"]


def code_points(unified):
    return [int(part, 16) for part in unified.split("-")]


def c_string(points):
    data = "".join(chr(cp) for cp in points).encode("utf-8")
    return '"' + "".join("\\x%02X" % b for b in data) + '"'


def derived_tone(points, tone):
    rest = points[1:]
    if rest and rest[0] == 0xFE0F:
        rest = rest[1:]
    return [points[0], int(tone, 16)] + rest


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_emoji_table.py emoji.json output.inc")
    source = sys.argv[1]
    raw = open(source, "rb").read()
    data = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()

    sequences = []   # (points, flags)
    names = []       # (name, index)
    overrides = []   # (index, [five point lists])
    for entry in sorted(data, key=lambda e: e.get("sort_order", 0)):
        points = code_points(entry["unified"])
        variations = entry.get("skin_variations") or {}
        index = len(sequences)
        flags = 0
        if variations:
            flags = 1
            single = [k for k in variations if "-" not in k]
            if single:
                for tone in TONES:
                    if tone in variations:
                        expected = derived_tone(points, tone)
                        actual = code_points(variations[tone]["unified"])
                        if expected != actual:
                            sys.exit("unexpected toned form for " + entry["short_name"])
            else:
                toned = []
                for tone in TONES:
                    key = tone + "-" + tone
                    if key not in variations:
                        break
                    toned.append(code_points(variations[key]["unified"]))
                if len(toned) == 5:
                    overrides.append((index, toned))
                else:
                    flags = 0
        sequences.append((points, flags))
        for name in entry["short_names"]:
            names.append((name, index))

    names.sort(key=lambda item: item[0].encode("utf-8"))
    for (a, _), (b, _) in zip(names, names[1:]):
        if a == b:
            sys.exit("duplicate short name " + a)

    out = []
    out.append("// Generated by tools/gen_emoji_table.py from iamcal/emoji-data")
    out.append("// (MIT, https://github.com/iamcal/emoji-data). Do not edit.")
    out.append("// emoji.json sha256 %s" % digest)
    out.append("// %d emoji, %d short names, %d tone overrides"
        % (len(sequences), len(names), len(overrides)))
    out.append("")
    out.append("static const EmojiSequence kEmojiSequences[] = {")
    for points, flags in sequences:
        out.append("\t{%s, %d}," % (c_string(points), flags))
    out.append("};")
    out.append("")
    out.append("static const EmojiName kEmojiNames[] = {")
    for name, index in names:
        out.append('\t{"%s", %d},' % (name, index))
    out.append("};")
    out.append("")
    out.append("static const EmojiToneOverride kToneOverrides[] = {")
    for index, toned in overrides:
        out.append("\t{%d, {%s}}," % (index, ", ".join(c_string(p) for p in toned)))
    out.append("};")
    out.append("")
    with open(sys.argv[2], "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))
    print("wrote %s: %d emoji, %d names, %d overrides"
        % (sys.argv[2], len(sequences), len(names), len(overrides)))


if __name__ == "__main__":
    main()
